FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app
COPY inventory/ .
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jdk-alpine
RUN apk add --no-cache curl
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]